input_dir: "/data/NCBR/rawdata/NCBR-410/assemblies"
result_dir: "/data/NCBR/rawdata/NCBR-410/brakerMake"
protein_file: "/data/NCBR/rawdata/NCBR-410/TriTrypDB-66_TbruceigambienseDAL972_AnnotatedProteins.fasta"
rna_dir: "/data/NCBR/rawdata/NCBR-410"
rna_list: "test1,test2,test3,SRR15328849,SRR15328850,SRR15328851,SRR15328852,SRR15328853,SRR15328854,SRR15328855,SRR15328856,SRR15328857,SRR15328858,SRR15328859,SRR15328860,SRR15328861,SRR15328862,SRR15328863,SRR15328864,SRR15328865,SRR15328866,SRR15328867,SRR15328868,SRR15328869,SRR15328870,SRR15328871,SRR15328872,SRR15328873,SRR15328874,SRR15328875,SRR15328876,SRR15328877,SRR15328878,SRR15328879,SRR15328880,SRR15328881,SRR15328882,SRR15328883,SRR15328884"
